name: Deploy on Dockerhub

on:
  workflow_run:
    workflows: ['Test FastAPI']
    types:
      - completed

jobs:
  deploy:
    # force reupdate
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "GIT_TAG=$TAG" >> $GITHUB_ENV
          echo "Tag is: $TAG"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/pythonapp:${{ env.GIT_TAG }}
