name: Deploy with Volume-Mounted Certs

on:
  workflow_run:
    workflows: ['Test FastAPI']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        id: versioning
        run: |
          VERSION=$(grep '^version\s*=' pyproject.toml | cut -d '"' -f2)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/pythonapp:latest
            ${{ vars.DOCKERHUB_USERNAME }}/pythonapp:${{ env.VERSION }}

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_SERVER_HOST }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/pythonapp:latest
            docker stop pythonapp || true
            docker rm pythonapp || true
            docker run -d \
              --name pythonapp \
              -p 443:443 \
              -v /etc/ssl/certs:/etc/ssl/certs \
              ${{ vars.DOCKERHUB_USERNAME }}/pythonapp:latest