name: Deploy on Dockerhub when Test is Completed

on:
  workflow_run:
    workflows: ['Test FastAPI']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: python-environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from pyproject.toml
        id: versioning
        run: |
          VERSION=$(grep '^version\s*=' pyproject.toml | head -1 | cut -d '"' -f2)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "Extracted version: $VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/pythonapp:latest
            ${{ vars.DOCKERHUB_USERNAME }}/pythonapp:${{ env.VERSION }}

      - name: SSH & Deploy to Server
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_SERVER_HOST }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/pythonapp:latest
            docker stop pythonapp || true
            docker rm pythonapp || true
            docker run -d --name pythonapp -p 443:443 ${{ vars.DOCKERHUB_USERNAME }}/pythonapp:latest
