name: Deploy on Dockerhub on Click

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker tag to deploy'
        required: true
        default: 'latest'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: python-environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/pythonapp:${{ github.event.inputs.tag }}
          
