name: Deploy on Dockerhub

on:
  workflow_run:
    workflows: ['Test FastAPI'] 
    # should be same name as what I am depending on
    # which is Test FastAPI as stated in test.yaml

    types:
      - completed

jobs:
  deploy:
    # This makes sure this job only runs if conclusion is success
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Extract version from tag
        run: |
          echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "Tag is: ${GITHUB_REF#refs/tags/}"

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{vars.DOCKERHUB_USERNAME}}/pythonapp:${{ env.GIT_TAG }}

  