name: Call Parrot Webhook

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger deployment webhook
        run: |
          curl -X POST https://webhook.siteownr.com/deploy \
            -H "Content-Type: application/json" \
            -d '{"secret": "'"${{ secrets.PARROT_WEBHOOK_SECRET }}"'"}'
