name: SSH Parrot

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: python-environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_SERVER_HOST }}  # or domain name
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "Connected via GitHub Actions!"
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/pythonapp:latest
            docker stop pythonapp || true
            docker rm pythonapp || true
            docker run -d --name pythonapp -p 8000:8000 ${{ vars.DOCKERHUB_USERNAME }}/pythonapp:latest
          
